export {default as Main} from './home'
export {default as Authen} from './authen'
export {default as Profile} from './profile'
export {default as Support} from './support'
export {default as Order} from './order'